/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7_davidzavala;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 50431
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Crear = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TErrores = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TSimbolos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        FTF_Alexico = new javax.swing.JFormattedTextField();
        FTF_ASintactico = new javax.swing.JFormattedTextField();
        FTF_OCodigo = new javax.swing.JFormattedTextField();
        FTF_Asemantico = new javax.swing.JFormattedTextField();
        FTF_GCodigo = new javax.swing.JFormattedTextField();
        FTF_CIntermedio = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TF_NombreCompilador = new javax.swing.JTextField();
        Evaluar = new javax.swing.JDialog();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        Crear.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        Crear.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setText("Analisis Lexico");
        Crear.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 85, -1, -1));

        jLabel9.setText("Ingrese los datos en la tabla correspondiente");
        Crear.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        jLabel10.setText("Simbolos");
        Crear.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        jLabel3.setText("Analisis Semantico");
        Crear.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel4.setText("Analisis Sintatico");
        Crear.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel6.setText("Codigo");
        Crear.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        jLabel7.setText("Optimizador de");
        Crear.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        TErrores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Variable"
            }
        ));
        jScrollPane1.setViewportView(TErrores);

        Crear.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 242, 50));

        TSimbolos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Variable"
            }
        ));
        jScrollPane2.setViewportView(TSimbolos);

        Crear.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 242, 50));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Crear.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 90, -1));

        try {
            FTF_Alexico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Crear.getContentPane().add(FTF_Alexico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 70, -1));

        try {
            FTF_ASintactico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Crear.getContentPane().add(FTF_ASintactico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 70, -1));

        try {
            FTF_OCodigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Crear.getContentPane().add(FTF_OCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 70, -1));

        try {
            FTF_Asemantico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Crear.getContentPane().add(FTF_Asemantico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 70, -1));

        try {
            FTF_GCodigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Crear.getContentPane().add(FTF_GCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 70, -1));

        try {
            FTF_CIntermedio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Crear.getContentPane().add(FTF_CIntermedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 70, -1));

        jLabel11.setText("Generacion de");
        Crear.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        jLabel12.setText("Codigo Intermedio");
        Crear.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jLabel13.setText("Codigo");
        Crear.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        jLabel14.setText("Generador de");
        Crear.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        jLabel15.setText("Errores");
        Crear.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, -1));
        Crear.getContentPane().add(TF_NombreCompilador, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 100, -1));

        javax.swing.GroupLayout EvaluarLayout = new javax.swing.GroupLayout(Evaluar.getContentPane());
        Evaluar.getContentPane().setLayout(EvaluarLayout);
        EvaluarLayout.setHorizontalGroup(
            EvaluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        EvaluarLayout.setVerticalGroup(
            EvaluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToggleButton1.setText("Crear Complador");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Evaluar Compilador");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jToggleButton1)
                .addGap(44, 44, 44)
                .addComponent(jToggleButton2)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        Crear.pack();
        Crear.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        Evaluar.pack();
        Evaluar.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    Usuario Usuariotemp;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int lineas = (Integer.parseInt(FTF_Alexico.getText())) + (Integer.parseInt(FTF_ASintactico.getText())) + (Integer.parseInt(FTF_Asemantico.getText())) + (Integer.parseInt(FTF_CIntermedio.getText())) + (Integer.parseInt(FTF_OCodigo.getText())) + (Integer.parseInt(FTF_GCodigo.getText()));
            Compilador C = new Compilador(TF_NombreCompilador.getText(), Usuariotemp, lineas, Integer.parseInt(FTF_Alexico.getText()), Integer.parseInt(FTF_ASintactico.getText()), Integer.parseInt(FTF_Asemantico.getText()), Integer.parseInt(FTF_CIntermedio.getText()), Integer.parseInt(FTF_OCodigo.getText()), Integer.parseInt(FTF_GCodigo.getText()));
            DefaultTableModel mod = (DefaultTableModel)TErrores.getModel();
            DefaultTableModel mod2 = (DefaultTableModel)TSimbolos.getModel();
            C.setErrores(mod);
            C.setSimbolos(mod2);
            AdminCompiladores AC = new AdminCompiladores("./compiladores.tpl");
            AC.CargarArchivo();
            AC.setCompilador(C);
            AC.EscribirArchivo();
            JOptionPane.showMessageDialog(null, "Guardado");
            CompiReset();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Algo ha salido mal");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void CompiReset() {
        TF_NombreCompilador.setText("");
        FTF_Alexico.setText("");
        FTF_ASintactico.setText("");
        FTF_Asemantico.setText("");
        FTF_CIntermedio.setText("");
        FTF_OCodigo.setText("");
        FTF_GCodigo.setText("");
    }

    public void UsuarioReset() {
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Crear;
    private javax.swing.JDialog Evaluar;
    private javax.swing.JFormattedTextField FTF_ASintactico;
    private javax.swing.JFormattedTextField FTF_Alexico;
    private javax.swing.JFormattedTextField FTF_Asemantico;
    private javax.swing.JFormattedTextField FTF_CIntermedio;
    private javax.swing.JFormattedTextField FTF_GCodigo;
    private javax.swing.JFormattedTextField FTF_OCodigo;
    private javax.swing.JTable TErrores;
    private javax.swing.JTextField TF_NombreCompilador;
    private javax.swing.JTable TSimbolos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
